<div class="frontpageinfo">
<h3>Hinnasto</h3>
<p>
<strong>Vuokrahinnat</strong>
<br>
<span style="text-decoration: underline;">MyPose</span>
<br>
Päivävuokra: 690 €
<br>
Lisäpäivät: 150 € / päivä
<br>
2 viikkoa: 1200 €
<br>
Yli 2 viikkoa: Pyydä erillinen tarjous
</p>
<p> </p>
<p>
<span style="text-decoration: underline;">Kuljetus ja asennus</span>
<br>
Normaali kuljetus: 490 €*
<br>
Kuljetus, suuri etäisyys: 690 €*
<br>
Pikatoimituslisä (alle 1 vko): 290 €
</p>
<p> </p>
<p style="padding-left: 30px;">*) Normaalin kuljetuksen alueet on määritetty ko. MyPose laitteen varaustiedoissa. Kaupungit jotka eivät ole listassa hinnoitellaan “Kuljetus, suuri etäisyys” mukaisesti.</p>
<p> </p>
<p>
<span style="text-decoration: underline;">Lisäpalvelut</span>
<br>
Kuvausvalo: 50 € /pv + 35 € / lisäpäivät
<br>
Promohenkilö: 350 € / pv / kpl
<br>
Graafinen suunnittelu:** 300 €
<br>
Markkinointiviestin päivitys: 100 € / kerta
<br>
Teemasomistus: Pyydä erillinen tarjous [ tuulia.hakamaki@magnumlive.fi ]
</p>
<p> </p>
<p style="padding-left: 30px;">**) Graafinen suunnittelu sisältää asiakkaan toiveiden mukaisen grafiikan/kampanjan rakentamisen ja asentamisen MyPose -laitteeseen.</p>
<p> </p>
<p>
<strong>KAIKKI HINNAT ALV 0%</strong>
</p>
<p> </p>
<p>
<strong>Vuokrahinta sisältää:</strong>
Raportointipalvelu statistiikkatiedon keräämiseen ja analysointiin sekä markkinointiviestin muokkaamisen. 4G verkkoyhteys (jos 4G yhteyttä ei ole saatavilla kytketään laite asennuksen yhteydessä saatavilla olevaan WLAN tai LAN verkkoon).
</p>
<p> </p>
<p>
<strong>Kuljetus ja asennus sisältävät:</strong>
Laitteen kuljetus ja nouto tapahtumapaikalle. Laitteen asentaminen toimitakuntoon. Toimintavalmiuden tarkastus ja testaus. Puhelintuki vikatilanteissa.
</p>
</div>
